#!/bin/ksh

DIR=$(dirname $(whence $0))
NODE=/opt/local/bin/node

export PATH=/usr/bin:/usr/sbin:$PATH
export MANPATH=$DIR/proto.man/usr/share/man

cd $DIR || exit 1
if [[ -t 0 ]]; then
  $NODE app | $NODE $DIR/node_modules/.bin/bunyan
else
  $NODE app
fi
